version: 2

updates:
  # Keep GitHub Actions dependencies up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'monthly'

  # Keep NuGet dependencies up-to-date
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: 'monthly'
