version: 2
jobs:
  build:
    working_directory: /exercism/xcsharp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: apt-get -qq update; apt-get -y install unzip
      - run: ./bin/fetch-configlet
      - run: ./bin/configlet lint .
      - run: ./build.sh
