version: 1

update_configs:
    - package_manager: "dotnet:nuget"
      directory: "/exercises"
      update_schedule: "live"
      automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "semver:minor"

    - package_manager: "dotnet:nuget"
      directory: "/generators"
      update_schedule: "live"
      automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "semver:minor"
