name: Configlet CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  configlet_without_format:
    uses: ErikSchierboom/github-actions-1/.github/workflows/configlet.yml@configlet-reusable-workflow

  configlet_with_format:
    uses: ErikSchierboom/github-actions-1/.github/workflows/configlet.yml@configlet-reusable-workflow
    with:
      format: true
