name: Configlet CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  configlet:
    uses: ErikSchierboom/github-actions-1/.github/workflows/configlet.yml@48f4a15d42520be77cbc3fb58c05e26247d69d5a
